// Elements of DOM
const $label = document.querySelector("label");
const $input = document.querySelector("input");
const $source = document.querySelector("source");
const $img = document.querySelector("img");
const $h2 = document.querySelector("h2");
const $follower = document.querySelector("#follower");
const $repo = document.querySelector("#repository");
const $job = document.querySelector("#job");